const crypto = require('crypto');
const {
  createRunOncePlugin,
  IOSConfig,
  withDangerousMod,
  withPodfile,
  withXcodeProject,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const packageJSON = require('./package.json');

const generatedMarker = '# @generated by expo-lynx';
const EMBEDDED_DIRECTORY = 'ExpoLynxEmbedded.bundle';
const EMBEDDED_PUBLIC_KEY = 'updates.public.pem';
const FEATURE_ID = /^[a-z][a-z0-9-]{0,63}$/;
const SHA_256 = /^[a-f0-9]{64}$/;
const MAX_PUBLIC_KEY_BYTES = 16 * 1024;
const MAX_ENTRIES = 4096;
const MAX_SINGLE_ENTRY_BYTES = 64 * 1024 * 1024;
const MAX_UNCOMPRESSED_BYTES = 256 * 1024 * 1024;

const rubyHelper = `${generatedMarker}
def expo_lynx_post_install(installer)
  lynx_targets = installer.pods_project.targets.select do |target|
    ['Lynx', 'BaseDevtool', 'LynxDevtool', 'LynxService'].include?(target.name)
  end
  return if lynx_targets.empty?

  disabled_warnings = [
    '-Wno-error',
    '-Wno-c99-designator',
    '-Wno-deprecated-declarations',
    '-Wno-deprecated-implementations',
  ]

  lynx_targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++20'
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      config.build_settings['CLANG_ENABLE_OBJC_WEAK'] = 'YES'

      ['OTHER_CPLUSPLUSFLAGS', 'OTHER_CFLAGS'].each do |key|
        flags = config.build_settings[key] || ['$(inherited)']
        flags = [flags] unless flags.is_a?(Array)
        config.build_settings[key] = (flags + disabled_warnings).uniq
      end
    end
  end
end
`;

function findClosingParenthesis(contents, openingIndex) {
  let depth = 0;
  let quote = null;
  let escaped = false;
  for (let index = openingIndex; index < contents.length; index += 1) {
    const character = contents[index];
    if (quote) {
      if (escaped) escaped = false;
      else if (character === '\\') escaped = true;
      else if (character === quote) quote = null;
      continue;
    }
    if (character === "'" || character === '"') quote = character;
    else if (character === '(') depth += 1;
    else if (character === ')') {
      depth -= 1;
      if (depth === 0) return index;
    }
  }
  return -1;
}

function addExpoLynxPostInstall(contents) {
  if (contents.includes(generatedMarker)) return contents;
  const functionIndex = contents.indexOf('react_native_post_install(');
  if (functionIndex === -1)
    throw new Error('expo-lynx could not find react_native_post_install in the iOS Podfile.');
  const openingIndex = contents.indexOf('(', functionIndex);
  const closingIndex = findClosingParenthesis(contents, openingIndex);
  if (closingIndex === -1)
    throw new Error('expo-lynx could not parse the react_native_post_install call.');
  return `${rubyHelper}\n${contents.slice(0, closingIndex + 1)}\n\n    expo_lynx_post_install(installer)${contents.slice(closingIndex + 1)}`;
}

function isPlainObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function assertKnownKeys(value, allowed, label) {
  if (!isPlainObject(value)) throw new Error(`expo-lynx ${label} must be an object.`);
  for (const key of Object.keys(value)) {
    if (!allowed.has(key))
      throw new Error(`expo-lynx ${label} contains an unsupported field: ${key}`);
  }
}

function assertRelativePath(value, optionName) {
  if (typeof value !== 'string' || !value.trim() || value.includes('\0')) {
    throw new Error(`expo-lynx ${optionName} must be one non-empty relative path.`);
  }
  if (path.isAbsolute(value) || value.startsWith('//') || /^[a-z][a-z0-9+.-]*:/i.test(value)) {
    throw new Error(`expo-lynx ${optionName} must be relative to the Expo app project root.`);
  }
  return value;
}

function isContained(root, candidate) {
  const relativePath = path.relative(root, candidate);
  return (
    relativePath === '' ||
    (!relativePath.startsWith(`..${path.sep}`) &&
      relativePath !== '..' &&
      !path.isAbsolute(relativePath))
  );
}

function resolveProjectPath(projectRoot, configuredPath, optionName, kind) {
  const relativePath = assertRelativePath(configuredPath, optionName);
  const lexical = path.resolve(projectRoot, relativePath);
  if (!isContained(projectRoot, lexical))
    throw new Error(`expo-lynx ${optionName} escapes the Expo app project root.`);
  if (!fs.existsSync(lexical))
    throw new Error(`expo-lynx ${optionName} does not exist: ${relativePath}`);
  // Resolve a symlink before checking its kind. An in-project symlink remains
  // valid, but the realpath containment check below rejects an escaped target.
  const stat = fs.statSync(lexical);
  if ((kind === 'file' && !stat.isFile()) || (kind === 'directory' && !stat.isDirectory())) {
    throw new Error(`expo-lynx ${optionName} must be a ${kind}.`);
  }
  const realProjectRoot = fs.realpathSync(projectRoot);
  const realPath = fs.realpathSync(lexical);
  if (!isContained(realProjectRoot, realPath))
    throw new Error(`expo-lynx ${optionName} resolves outside the Expo app project root.`);
  return realPath;
}

function normalizePublicKey(sourcePath) {
  if (!path.basename(sourcePath).endsWith('.public.pem')) {
    throw new Error('expo-lynx publicKeyPath must end with .public.pem.');
  }
  const size = fs.statSync(sourcePath).size;
  if (size <= 0 || size > MAX_PUBLIC_KEY_BYTES)
    throw new Error('expo-lynx publicKeyPath must be a UTF-8 file no larger than 16 KiB.');
  const raw = fs.readFileSync(sourcePath);
  let pem;
  try {
    pem = new TextDecoder('utf-8', { fatal: true }).decode(raw);
  } catch {
    throw new Error('expo-lynx publicKeyPath must be valid UTF-8.');
  }
  const normalized = `${pem.replace(/\r\n?/g, '\n').trimEnd()}\n`;
  if (/PRIVATE KEY|BEGIN CERTIFICATE|BEGIN RSA PUBLIC KEY/.test(normalized)) {
    throw new Error(
      'expo-lynx publicKeyPath must contain one SPKI public key, never a private key or certificate.'
    );
  }
  const blocks = normalized.match(/-----BEGIN [^-]+-----[\s\S]*?-----END [^-]+-----/g) ?? [];
  if (blocks.length !== 1 || blocks[0] !== normalized.trim())
    throw new Error('expo-lynx publicKeyPath must contain exactly one PEM block.');
  if (
    !normalized.startsWith('-----BEGIN PUBLIC KEY-----\n') ||
    !normalized.endsWith('-----END PUBLIC KEY-----\n')
  ) {
    throw new Error('expo-lynx publicKeyPath must be a SubjectPublicKeyInfo PEM public key.');
  }
  let key;
  try {
    key = crypto.createPublicKey(normalized);
  } catch {
    throw new Error('expo-lynx publicKeyPath is not a parseable SPKI public key.');
  }
  const details = key.asymmetricKeyDetails;
  if (
    key.asymmetricKeyType !== 'rsa' ||
    !details ||
    details.modulusLength < 3072 ||
    Number(details.publicExponent) !== 65537
  ) {
    throw new Error(
      'expo-lynx publicKeyPath must be RSA with a 3072-bit-or-larger modulus and exponent 65537.'
    );
  }
  const der = key.export({ type: 'spki', format: 'der' });
  return {
    pem: normalized,
    fingerprint: crypto.createHash('sha256').update(der).digest('base64url'),
  };
}

function assertFeature(value, label) {
  if (typeof value !== 'string' || !FEATURE_ID.test(value))
    throw new Error(`expo-lynx ${label} has an invalid feature key.`);
}

function assertSafeRelativePath(value, label) {
  if (
    typeof value !== 'string' ||
    !value ||
    value.startsWith('/') ||
    value.includes('\\') ||
    value.includes('\0')
  ) {
    throw new Error(`expo-lynx ${label} has an unsafe path.`);
  }
  const parts = value.split('/');
  if (parts.length > 16 || parts.some((part) => !part || part === '.' || part === '..'))
    throw new Error(`expo-lynx ${label} has an unsafe path.`);
}

function assertHash(value, label) {
  if (typeof value !== 'string' || !SHA_256.test(value))
    throw new Error(`expo-lynx ${label} has an invalid SHA-256.`);
}

function parseJSONFile(filePath, label) {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch {
    throw new Error(`expo-lynx ${label} is not valid JSON.`);
  }
}

function resolveEmbeddedPath(root, relativePath, label) {
  assertSafeRelativePath(relativePath, label);
  const absolute = path.resolve(root, relativePath);
  if (!isContained(root, absolute))
    throw new Error(`expo-lynx ${label} escapes the embedded bundle root.`);
  if (!fs.existsSync(absolute) || !fs.lstatSync(absolute).isFile())
    throw new Error(`expo-lynx ${label} is missing or not a regular file.`);
  const realRoot = fs.realpathSync(root);
  const realPath = fs.realpathSync(absolute);
  if (!isContained(realRoot, realPath))
    throw new Error(`expo-lynx ${label} resolves outside the embedded bundle root.`);
  return realPath;
}

function runtimeFiles(featureDirectory) {
  const files = [];
  const walk = (directory, prefix = '') => {
    for (const entry of fs
      .readdirSync(directory, { withFileTypes: true })
      .sort((a, b) => a.name.localeCompare(b.name))) {
      const absolute = path.join(directory, entry.name);
      const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isSymbolicLink() || entry.name.startsWith('.'))
        throw new Error(`expo-lynx embedded output contains a forbidden entry: ${relativePath}`);
      if (entry.isDirectory()) walk(absolute, relativePath);
      else if (entry.isFile()) {
        if (relativePath !== 'baseline.json') {
          assertSafeRelativePath(relativePath, `embedded output ${relativePath}`);
          files.push({
            path: relativePath,
            bytes: fs.statSync(absolute).size,
            sha256: crypto.createHash('sha256').update(fs.readFileSync(absolute)).digest('hex'),
          });
        }
      } else
        throw new Error(`expo-lynx embedded output contains an unsupported entry: ${relativePath}`);
    }
  };
  walk(featureDirectory);
  return files;
}

function validateEmbeddedBundles(sourcePath) {
  const registryPath = resolveEmbeddedPath(sourcePath, 'registry.json', 'embedded registry');
  const registry = parseJSONFile(registryPath, 'embedded registry');
  if (
    !isPlainObject(registry) ||
    registry.schemaVersion !== 1 ||
    typeof registry.runtimeVersion !== 'string' ||
    !registry.runtimeVersion ||
    !isPlainObject(registry.features)
  ) {
    throw new Error('expo-lynx embedded registry is malformed.');
  }
  const features = Object.keys(registry.features).sort();
  if (features.length === 0)
    throw new Error('expo-lynx embedded registry must declare at least one feature.');
  const expectedTopLevel = new Set(['registry.json', ...features]);
  for (const entry of fs.readdirSync(sourcePath, { withFileTypes: true })) {
    if (
      !expectedTopLevel.has(entry.name) ||
      entry.isSymbolicLink() ||
      (entry.name !== 'registry.json' && !entry.isDirectory())
    ) {
      throw new Error(`expo-lynx embedded output has an unexpected top-level entry: ${entry.name}`);
    }
  }
  for (const feature of features) {
    assertFeature(feature, 'embedded registry');
    const registryEntry = registry.features[feature];
    if (
      !isPlainObject(registryEntry) ||
      registryEntry.baseline !== `${feature}/baseline.json` ||
      registryEntry.entry !== `${feature}/main.lynx.bundle`
    ) {
      throw new Error(`expo-lynx embedded registry entry is invalid for ${feature}.`);
    }
    const featureDirectory = path.resolve(sourcePath, feature);
    if (
      !isContained(sourcePath, featureDirectory) ||
      !fs.existsSync(featureDirectory) ||
      !fs.lstatSync(featureDirectory).isDirectory()
    ) {
      throw new Error(`expo-lynx embedded feature directory is missing for ${feature}.`);
    }
    const baselinePath = resolveEmbeddedPath(
      sourcePath,
      registryEntry.baseline,
      `embedded baseline ${feature}`
    );
    const baseline = parseJSONFile(baselinePath, `embedded baseline ${feature}`);
    if (
      !isPlainObject(baseline) ||
      baseline.schemaVersion !== 1 ||
      baseline.feature !== feature ||
      baseline.runtimeVersion !== registry.runtimeVersion ||
      baseline.entry !== 'main.lynx.bundle' ||
      !Array.isArray(baseline.files) ||
      typeof baseline.inputFingerprint !== 'string' ||
      !SHA_256.test(baseline.inputFingerprint)
    ) {
      throw new Error(`expo-lynx embedded baseline is malformed for ${feature}.`);
    }
    const actual = runtimeFiles(featureDirectory);
    if (!actual.some((file) => file.path === 'main.lynx.bundle'))
      throw new Error(`expo-lynx embedded baseline is missing main.lynx.bundle for ${feature}.`);
    if (
      actual.length > MAX_ENTRIES ||
      actual.reduce((total, file) => total + file.bytes, 0) > MAX_UNCOMPRESSED_BYTES
    )
      throw new Error(`expo-lynx embedded baseline exceeds delivery limits for ${feature}.`);
    const declared = baseline.files.map((file) => {
      if (!isPlainObject(file))
        throw new Error(`expo-lynx embedded baseline has an invalid file entry for ${feature}.`);
      assertSafeRelativePath(file.path, `embedded baseline ${feature}`);
      if (file.path !== 'main.lynx.bundle' && !file.path.startsWith('static/'))
        throw new Error(
          `expo-lynx embedded baseline has an unsupported file for ${feature}: ${file.path}`
        );
      if (
        !Number.isSafeInteger(file.bytes) ||
        file.bytes <= 0 ||
        file.bytes > MAX_SINGLE_ENTRY_BYTES
      )
        throw new Error(`expo-lynx embedded baseline has an invalid file size for ${feature}.`);
      assertHash(file.sha256, `embedded baseline ${feature}`);
      return { path: file.path, bytes: file.bytes, sha256: file.sha256 };
    });
    if (JSON.stringify(actual) !== JSON.stringify(declared))
      throw new Error(`expo-lynx embedded baseline is stale or incomplete for ${feature}.`);
  }
  return { registry, features };
}

function copyBundledResource(sourcePath, destinationPath) {
  if (fs.statSync(sourcePath).isDirectory())
    fs.cpSync(sourcePath, destinationPath, { recursive: true, force: true, dereference: false });
  else fs.copyFileSync(sourcePath, destinationPath);
}

function markResourceDirectoryAsFolder(project, xcodePath) {
  const normalizedPath = xcodePath.replace(/\\/g, '/');
  for (const [key, reference] of Object.entries(project.pbxFileReferenceSection())) {
    if (key.endsWith('_comment') || !reference || typeof reference !== 'object') continue;
    const referencePath = String(reference.path || '').replace(/^"|"$/g, '');
    if (referencePath !== normalizedPath) continue;
    reference.lastKnownFileType = 'folder';
    delete reference.explicitFileType;
    delete reference.fileEncoding;
    return;
  }
  throw new Error(`expo-lynx could not mark the iOS resource directory as a folder: ${xcodePath}`);
}

function addResource(project, nativeProjectName, xcodePath, isDirectory) {
  if (!project.hasFile(xcodePath)) {
    project = IOSConfig.XcodeUtils.addResourceFileToGroup({
      filepath: xcodePath,
      groupName: nativeProjectName,
      isBuildFile: true,
      project,
    });
  }
  if (isDirectory) markResourceDirectoryAsFolder(project, xcodePath);
  return project;
}

function validateV2Options(options) {
  const hasEmbedded = options.embeddedBundlesPath !== undefined;
  const hasKey = options.publicKeyPath !== undefined;
  if (hasEmbedded !== hasKey)
    throw new Error('expo-lynx embeddedBundlesPath and publicKeyPath must be configured together.');
  if (!hasEmbedded) return null;
  assertKnownKeys(
    options,
    new Set(['bundledResources', 'embeddedBundlesPath', 'publicKeyPath']),
    'plugin options'
  );
  if (Array.isArray(options.bundledResources) && options.bundledResources.length > 0) {
    throw new Error(
      'expo-lynx bundledResources cannot be combined with V2 embeddedBundlesPath; it would duplicate shipped Lynx bytes.'
    );
  }
  return { embeddedBundlesPath: options.embeddedBundlesPath, publicKeyPath: options.publicKeyPath };
}

function materializeV2Resources({ projectRoot, platformProjectRoot, nativeProjectName, options }) {
  const sourcePath = resolveProjectPath(
    projectRoot,
    options.embeddedBundlesPath,
    'embeddedBundlesPath',
    'directory'
  );
  const publicKeyPath = resolveProjectPath(
    projectRoot,
    options.publicKeyPath,
    'publicKeyPath',
    'file'
  );
  const { registry } = validateEmbeddedBundles(sourcePath);
  const publicKey = normalizePublicKey(publicKeyPath);
  const destinationPath = path.join(platformProjectRoot, nativeProjectName, EMBEDDED_DIRECTORY);
  // This is a plugin-owned generated directory. Replacing it as a unit keeps
  // removed sidecars from surviving a subsequent prebuild.
  fs.rmSync(destinationPath, { recursive: true, force: true });
  fs.mkdirSync(destinationPath, { recursive: true });
  copyBundledResource(sourcePath, destinationPath);
  fs.writeFileSync(path.join(destinationPath, EMBEDDED_PUBLIC_KEY), publicKey.pem, {
    encoding: 'utf8',
    mode: 0o644,
  });
  fs.writeFileSync(
    path.join(destinationPath, 'trust.json'),
    `${JSON.stringify({ schemaVersion: 1, algorithm: 'RSA-SHA256', fingerprint: publicKey.fingerprint, runtimeVersion: registry.runtimeVersion })}\n`,
    { encoding: 'utf8', mode: 0o644 }
  );
  return destinationPath;
}

function withV2EmbeddedResources(config, v2Options) {
  if (!v2Options) return config;
  return withXcodeProject(config, (projectConfig) => {
    const { platformProjectRoot, projectName, projectRoot } = projectConfig.modRequest;
    const nativeProjectName = projectName || IOSConfig.XcodeUtils.getProjectName(projectRoot);
    materializeV2Resources({
      projectRoot,
      platformProjectRoot,
      nativeProjectName,
      options: v2Options,
    });
    projectConfig.modResults = addResource(
      projectConfig.modResults,
      nativeProjectName,
      `${nativeProjectName}/${EMBEDDED_DIRECTORY}`,
      true
    );
    return projectConfig;
  });
}

function withBundledResources(config, bundledResources) {
  if (!bundledResources.length) return config;
  config = withXcodeProject(config, (projectConfig) => {
    const { platformProjectRoot, projectName, projectRoot } = projectConfig.modRequest;
    const nativeProjectName = projectName || IOSConfig.XcodeUtils.getProjectName(projectRoot);
    for (const resourcePath of bundledResources) {
      const sourcePath = path.resolve(projectRoot, resourcePath);
      if (!fs.existsSync(sourcePath))
        throw new Error(`expo-lynx bundled resource does not exist: ${resourcePath}`);
      const filename = path.basename(sourcePath);
      const xcodePath = `${nativeProjectName}/${filename}`;
      copyBundledResource(sourcePath, path.join(platformProjectRoot, nativeProjectName, filename));
      projectConfig.modResults = addResource(
        projectConfig.modResults,
        nativeProjectName,
        xcodePath,
        fs.statSync(sourcePath).isDirectory()
      );
    }
    return projectConfig;
  });
  return withDangerousMod(config, [
    'android',
    (androidConfig) => {
      const { projectRoot } = androidConfig.modRequest;
      const androidAssetsDir = path.join(projectRoot, 'android', 'app', 'src', 'main', 'assets');
      fs.mkdirSync(androidAssetsDir, { recursive: true });
      for (const resourcePath of bundledResources) {
        const sourcePath = path.resolve(projectRoot, resourcePath);
        if (!fs.existsSync(sourcePath))
          throw new Error(`expo-lynx bundled resource does not exist: ${resourcePath}`);
        copyBundledResource(sourcePath, path.join(androidAssetsDir, path.basename(sourcePath)));
      }
      return androidConfig;
    },
  ]);
}

const withExpoLynx = (config, options = {}) => {
  const v2Options = validateV2Options(options);
  const bundledResources = options.bundledResources || [];
  if (
    !Array.isArray(bundledResources) ||
    !bundledResources.every((value) => typeof value === 'string')
  )
    throw new Error('expo-lynx bundledResources must be a string array.');
  config = withPodfile(config, (podfileConfig) => {
    podfileConfig.modResults.contents = addExpoLynxPostInstall(podfileConfig.modResults.contents);
    return podfileConfig;
  });
  config = withV2EmbeddedResources(config, v2Options);
  return withBundledResources(config, bundledResources);
};

const plugin = createRunOncePlugin(withExpoLynx, packageJSON.name, packageJSON.version);
module.exports = plugin;
module.exports._internal = {
  EMBEDDED_DIRECTORY,
  EMBEDDED_PUBLIC_KEY,
  addExpoLynxPostInstall,
  addResource,
  materializeV2Resources,
  normalizePublicKey,
  resolveProjectPath,
  validateEmbeddedBundles,
  validateV2Options,
};
