/* global __dirname */

const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const test = require('node:test');

const { _internal } = require('./app.plugin');

const fixtureRoot = path.join(__dirname, 'feature/delivery-bundle-update/fixtures/v2');

test('adds opt-in internal Release flags to the ExpoLynx pod post-install hook', () => {
  const podfile = `target 'Example' do\n  post_install do |installer|\n    react_native_post_install(\n      installer,\n      '../node_modules/react-native',\n    )\n  end\nend\n`;
  const updated = _internal.addExpoLynxPostInstall(podfile);

  assert.match(updated, /target\.name == 'ExpoLynx'/);
  assert.match(updated, /config\.name == 'Release'/);
  assert.match(updated, /LYNX_ALLOW_LOCAL_MANAGED_RELEASE/);
  assert.match(updated, /LYNX_IFR_METRICS/);
  assert.match(updated, /conditions\.reject/);
  assert.equal((updated.match(/expo_lynx_post_install\(installer\)/g) ?? []).length, 2);
});

test('upgrades the legacy generated Podfile hook without duplicating it', () => {
  const podfile = `# @generated by expo-lynx\ndef expo_lynx_post_install(installer)\n  return\nend\n\nrequire 'expo'\n\ntarget 'Example' do\n  post_install do |installer|\n    react_native_post_install(installer)\n\n    expo_lynx_post_install(installer)\n  end\nend\n`;
  const updated = _internal.addExpoLynxPostInstall(podfile);

  assert.match(updated, /^# @generated by expo-lynx-view/);
  assert.doesNotMatch(updated, /\n  return\n/);
  assert.equal((updated.match(/def expo_lynx_post_install/g) ?? []).length, 1);
  assert.equal((updated.match(/expo_lynx_post_install\(installer\)/g) ?? []).length, 2);
});

test('adds the lynx-family Specs source before platform :ios', () => {
  const podfile = `require 'json'\nplatform :ios, '16.4'\n\nprepare_react_native_project!\n`;
  const updated = _internal.addExpoLynxSpecsSource(podfile);

  assert.match(updated, /source 'https:\/\/cdn\.cocoapods\.org\/'/);
  assert.match(updated, /source 'https:\/\/github\.com\/lynx-family\/Specs\.git'/);
  assert.ok(updated.indexOf("source 'https://github.com/lynx-family/Specs.git'") < updated.indexOf('platform :ios'));
});

test('does not duplicate the Specs source on a second, non-clean prebuild', () => {
  const podfile = `platform :ios, '16.4'\n`;
  const once = _internal.addExpoLynxSpecsSource(podfile);
  const twice = _internal.addExpoLynxSpecsSource(once);

  assert.equal(once, twice);
  assert.equal((twice.match(/source 'https:\/\/github\.com\/lynx-family\/Specs\.git'/g) ?? []).length, 1);
});

test('allows non-modular includes in framework modules project-wide, for the precompiled Lynx.xcframework', () => {
  // Regression test: the precompiled Lynx.xcframework (devTool: false) has
  // its own baked-in module.modulemap, so Xcode explicit-modules-builds it,
  // and its umbrella header imports LynxServiceAPI's plain (non-modular)
  // headers. Confirmed with a real `xcodebuild`: PrecompileModule for Lynx
  // failed with "[-Werror,-Wnon-modular-include-in-framework-module]" until
  // this setting was applied to every target in the Pods project (the
  // module can be triggered by whichever target imports Lynx first).
  const podfile = `target 'Example' do\n  post_install do |installer|\n    react_native_post_install(\n      installer,\n      '../node_modules/react-native',\n    )\n  end\nend\n`;
  const updated = _internal.addExpoLynxPostInstall(podfile);

  assert.match(updated, /pods_project\.targets\.each/);
  assert.match(updated, /CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'\] = 'YES'/);
});

test('restores gnu++20 for XElement, undoing react_native_post_install\'s global c++20', () => {
  // Regression test: react_native_post_install forces
  // CLANG_CXX_LANGUAGE_STANDARD='c++20' (strict ISO) project-wide,
  // overriding XElement's own xcconfig-declared 'gnu++17'. Strict C++20
  // breaks Clang's `typeof` GNU extension in ObjC++ ARC code — confirmed
  // with a real `xcodebuild`: LynxSVGRenderer.mm's
  // `__weak typeof(self) weakSelf = self;` failed with "expected
  // unqualified-id" under -std=c++20 and compiled clean under -std=gnu++20.
  const podfile = `target 'Example' do\n  post_install do |installer|\n    react_native_post_install(\n      installer,\n      '../node_modules/react-native',\n    )\n  end\nend\n`;
  const updated = _internal.addExpoLynxPostInstall(podfile);

  assert.match(updated, /\['Lynx', 'BaseDevtool', 'LynxDevtool', 'LynxService', 'XElement'\]/);
  assert.match(updated, /CLANG_CXX_LANGUAGE_STANDARD'\] = 'gnu\+\+20'/);
});

test('disables the header map for ServalSVG and ServalMarkdown in the post-install hook', () => {
  // Regression test: without USE_HEADERMAP=NO, ServalSVG's / ServalMarkdown's
  // plain `#include "stdlib.h"` / `#include "stdio.h"` resolves through
  // Xcode's project-wide header map to ReactNativeDependencies' bundled
  // folly/portability/{Stdlib,Stdio}.h instead of the real system header —
  // confirmed by a real `xcodebuild`, which failed with "'folly/CPortability.h'
  // file not found" (then "'cstdio' file not found") from inside that shim
  // until this setting was added to each target in turn.
  const podfile = `target 'Example' do\n  post_install do |installer|\n    react_native_post_install(\n      installer,\n      '../node_modules/react-native',\n    )\n  end\nend\n`;
  const updated = _internal.addExpoLynxPostInstall(podfile);

  assert.match(updated, /\['ServalSVG', 'ServalMarkdown'\]/);
  assert.match(updated, /USE_HEADERMAP'\] = 'NO'/);
});

test('adds the precompiled Lynx :path pod, right before use_expo_modules!', () => {
  const podfile = `target 'Example' do\n  use_expo_modules!\nend\n`;
  const updated = _internal.addExpoLynxPrecompiledPod(podfile);

  const precompiledPath = path.join(__dirname, 'ios', 'Precompiled');
  assert.ok(updated.includes(`pod 'Lynx', :path => '${precompiledPath}'`));
  assert.ok(updated.indexOf("pod 'Lynx'") < updated.indexOf('use_expo_modules!'));
});

test('does not duplicate the precompiled Lynx pod on a second, non-clean prebuild', () => {
  const podfile = `target 'Example' do\n  use_expo_modules!\nend\n`;
  const once = _internal.addExpoLynxPrecompiledPod(podfile);
  const twice = _internal.addExpoLynxPrecompiledPod(once);

  assert.equal(once, twice);
  assert.equal((twice.match(/pod 'Lynx', :path/g) ?? []).length, 1);
});

test('removes the precompiled Lynx :path pod when devTool is toggled on', () => {
  // Regression test: LynxDevtool is source-built and needs Lynx's full
  // nested C++ header tree (see addExpoLynxPrecompiledPod's comment) — a
  // stale :path override from a prior devTool:false prebuild must not
  // survive into a devTool:true one.
  const podfile = `target 'Example' do\n  use_expo_modules!\nend\n`;
  const withPrecompiled = _internal.addExpoLynxPrecompiledPod(podfile);
  const removed = _internal.removeExpoLynxPrecompiledPod(withPrecompiled);

  assert.doesNotMatch(removed, /pod 'Lynx', :path/);
  assert.match(removed, /use_expo_modules!/);
});

test('adds LynxService/Devtool scoped to Debug only, right before use_expo_modules!', () => {
  const podfile = `target 'Example' do\n  pod 'Lynx'\n  use_expo_modules!\n\n  config = use_native_modules!\nend\n`;
  const updated = _internal.addExpoLynxDevtoolPod(podfile);

  assert.match(updated, /pod 'LynxService\/Devtool', '4\.1\.0', :configurations => \['Debug'\]/);
  assert.ok(updated.indexOf("pod 'LynxService/Devtool'") < updated.indexOf('use_expo_modules!'));
});

test('also scopes LynxDevtool, BaseDevtool, and DebugRouter to Debug — :configurations does not propagate to transitive deps', () => {
  // Regression test: CocoaPods only restricts the exact pod line it's
  // attached to. Scoping LynxService/Devtool alone still links its
  // dependencies (LynxDevtool, BaseDevtool, DebugRouter) into Release —
  // confirmed by inspecting a real `pod install`'s generated
  // Pods-*.release.xcconfig, which had `-lLynxDevtool -lBaseDevtool
  // -lDebugRouter` in OTHER_LDFLAGS despite the Debug-only devtool line.
  const podfile = `target 'Example' do\n  use_expo_modules!\nend\n`;
  const updated = _internal.addExpoLynxDevtoolPod(podfile);

  for (const line of [
    "pod 'LynxDevtool', '4.1.0', :configurations => ['Debug']",
    "pod 'BaseDevtool', '4.1.0', :configurations => ['Debug']",
    "pod 'DebugRouter', '5.0.15', :configurations => ['Debug']",
  ]) {
    assert.ok(updated.includes(line), `expected Podfile to include: ${line}`);
  }
});

test('does not duplicate the devtool pods on a second, non-clean prebuild', () => {
  const podfile = `target 'Example' do\n  use_expo_modules!\nend\n`;
  const once = _internal.addExpoLynxDevtoolPod(podfile);
  const twice = _internal.addExpoLynxDevtoolPod(once);

  assert.equal(once, twice);
  for (const name of ['LynxService/Devtool', 'LynxDevtool', 'BaseDevtool', 'DebugRouter']) {
    assert.equal((twice.match(new RegExp(`pod '${name}'`, 'g')) ?? []).length, 1, name);
  }
});

test('re-merges the devtool pod when the pinned version changes on a later prebuild', () => {
  // Simulate what an older plugin version would have generated (a real
  // Podfile carried over from a non-clean prebuild before a version bump),
  // by merging with an old pin instead of hand-editing the generated block.
  const podfile = `target 'Example' do\n  use_expo_modules!\nend\n`;
  const { contents: stale } = _internal.mergeContents({
    tag: 'expo-lynx-view-devtool',
    src: podfile,
    newSrc: "  pod 'LynxService/Devtool', '4.0.0', :configurations => ['Debug']",
    anchor: /use_expo_modules!/,
    offset: 0,
    comment: '#',
  });

  const updated = _internal.addExpoLynxDevtoolPod(stale);

  assert.match(updated, /pod 'LynxService\/Devtool', '4\.1\.0'/);
  assert.doesNotMatch(updated, /'4\.0\.0'/);
  assert.equal((updated.match(/pod 'LynxService\/Devtool'/g) ?? []).length, 1);
});

test('removes a previously injected devtool pod when devTool is toggled off', () => {
  const podfile = `target 'Example' do\n  use_expo_modules!\nend\n`;
  const withDevtool = _internal.addExpoLynxDevtoolPod(podfile);
  const removed = _internal.removeExpoLynxDevtoolPod(withDevtool);

  assert.doesNotMatch(removed, /pod 'LynxService\/Devtool'/);
  assert.match(removed, /use_expo_modules!/);
});

test('removing the devtool pod is a no-op when it was never injected', () => {
  const podfile = `target 'Example' do\n  use_expo_modules!\nend\n`;
  const removed = _internal.removeExpoLynxDevtoolPod(podfile);

  assert.equal(removed, podfile);
});

test('devTool is accepted alongside V2 embeddedBundlesPath options', () => {
  assert.doesNotThrow(() =>
    _internal.validateV2Options({
      embeddedBundlesPath: './embedded',
      publicKeyPath: './updates.public.pem',
      devTool: false,
    })
  );
});

test('resolveDevToolOption defaults to true and validates the type', () => {
  assert.equal(_internal.resolveDevToolOption({}), true);
  assert.equal(_internal.resolveDevToolOption({ devTool: true }), true);
  assert.equal(_internal.resolveDevToolOption({ devTool: false }), false);
  assert.throws(() => _internal.resolveDevToolOption({ devTool: 'yes' }), {
    message: 'expo-lynx-view devTool must be a boolean.',
  });
});

test('prefers precompiled ExpoImage in both app configurations without changing sibling targets', () => {
  const expoImagePath = '"$(PODS_XCFRAMEWORKS_BUILD_DIR)/ExpoImage"';
  const debug = { buildSettings: { FRAMEWORK_SEARCH_PATHS: ['$(inherited)', expoImagePath] } };
  const release = { buildSettings: { FRAMEWORK_SEARCH_PATHS: '$(inherited)' } };
  const extension = { buildSettings: { FRAMEWORK_SEARCH_PATHS: ['$(inherited)'] } };
  const project = {
    pbxNativeTargetSection: () => ({
      APP: { productType: '"com.apple.product-type.application"', buildConfigurationList: 'APP_LIST' },
      EXTENSION: { productType: '"com.apple.product-type.app-extension"', buildConfigurationList: 'EXTENSION_LIST' },
    }),
    pbxXCConfigurationList: () => ({
      APP_LIST: { buildConfigurations: [{ value: 'DEBUG' }, { value: 'RELEASE' }] },
      EXTENSION_LIST: { buildConfigurations: [{ value: 'EXTENSION_DEBUG' }] },
    }),
    pbxXCBuildConfigurationSection: () => ({ DEBUG: debug, RELEASE: release, EXTENSION_DEBUG: extension }),
  };

  _internal.prioritizeExpoImageFramework(project);
  _internal.prioritizeExpoImageFramework(project);
  assert.deepEqual(debug.buildSettings.FRAMEWORK_SEARCH_PATHS, [expoImagePath, '"$(inherited)"']);
  assert.deepEqual(release.buildSettings.FRAMEWORK_SEARCH_PATHS, [expoImagePath, '"$(inherited)"']);
  assert.deepEqual(extension.buildSettings.FRAMEWORK_SEARCH_PATHS, ['$(inherited)']);
});

test('resolves expo-image from the consuming app when available', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'expo-lynx-image-'));
  assert.equal(_internal.hasExpoImage(root), false);
  const imageDirectory = path.join(root, 'node_modules/expo-image');
  fs.mkdirSync(imageDirectory, { recursive: true });
  fs.writeFileSync(path.join(imageDirectory, 'package.json'), '{"name":"expo-image"}');
  assert.equal(_internal.hasExpoImage(root), true);
});

function makeTemporaryEmbeddedTree() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'expo-lynx-plugin-'));
  const embedded = path.join(root, 'generated/expo-lynx/embedded');
  const feature = path.join(embedded, 'shopping');
  fs.mkdirSync(path.join(feature, 'static'), { recursive: true });
  fs.writeFileSync(path.join(feature, 'main.lynx.bundle'), 'mini-app');
  fs.writeFileSync(path.join(feature, 'static/logo.txt'), 'logo');
  const files = ['main.lynx.bundle', 'static/logo.txt'].map((relativePath) => {
    const content = fs.readFileSync(path.join(feature, relativePath));
    return {
      path: relativePath,
      bytes: content.length,
      sha256: crypto.createHash('sha256').update(content).digest('hex'),
    };
  });
  fs.writeFileSync(
    path.join(feature, 'baseline.json'),
    JSON.stringify({
      schemaVersion: 2,
      feature: 'shopping',
      entry: 'main.lynx.bundle',
      files,
    })
  );
  fs.writeFileSync(
    path.join(embedded, 'registry.json'),
    JSON.stringify({
      schemaVersion: 2,
      features: {
        shopping: { baseline: 'shopping/baseline.json' },
      },
      runtimes: {
        ios: { runtimeVersion: 'ios:expo-57', appVersion: '1.0.0', buildNumber: '1' },
        android: { runtimeVersion: 'android:expo-57', appVersion: '1.0.0', buildNumber: '1' },
      },
    })
  );
  return { root, embedded, feature };
}

test('validates a complete S01 embedded tree and rejects a stale sidecar', () => {
  const { embedded, feature } = makeTemporaryEmbeddedTree();
  assert.deepEqual(_internal.validateEmbeddedBundles(embedded).features, ['shopping']);
  fs.writeFileSync(path.join(feature, 'static/logo.txt'), 'changed');
  assert.throws(() => _internal.validateEmbeddedBundles(embedded), /stale or incomplete/);
});

test('normalizes only RSA 3072 SPKI public keys and computes an opaque fingerprint', () => {
  const publicKey = path.join(fixtureRoot, 'crypto-development/updates.public.pem');
  const normalized = _internal.normalizePublicKey(publicKey);
  assert.match(normalized.pem, /^-----BEGIN PUBLIC KEY-----/);
  assert.match(normalized.fingerprint, /^[A-Za-z0-9_-]{43}$/);

  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'expo-lynx-pem-'));
  const privateKey = path.join(root, 'updates.public.pem');
  const privateMarker = 'PRIVATE KEY';
  fs.writeFileSync(
    privateKey,
    `-----BEGIN ${privateMarker}-----\ninvalid\n-----END ${privateMarker}-----\n`
  );
  assert.throws(() => _internal.normalizePublicKey(privateKey), /private key/);
});

test('resolves prebuild inputs from the Expo app root and rejects lexical or symlink escapes', () => {
  const { root, embedded } = makeTemporaryEmbeddedTree();
  const publicKeyDir = path.join(root, 'keys/lynx');
  fs.mkdirSync(publicKeyDir, { recursive: true });
  fs.copyFileSync(
    path.join(fixtureRoot, 'crypto-development/updates.public.pem'),
    path.join(publicKeyDir, 'updates.public.pem')
  );
  assert.equal(
    _internal.resolveProjectPath(
      root,
      './generated/expo-lynx/embedded',
      'embeddedBundlesPath',
      'directory'
    ),
    fs.realpathSync(embedded)
  );
  assert.throws(
    () => _internal.resolveProjectPath(root, '../outside', 'embeddedBundlesPath', 'directory'),
    /escapes/
  );
  assert.throws(
    () =>
      _internal.resolveProjectPath(root, 'https://example.com/key.pem', 'publicKeyPath', 'file'),
    /relative/
  );

  const external = fs.mkdtempSync(path.join(os.tmpdir(), 'expo-lynx-external-'));
  fs.symlinkSync(external, path.join(root, 'escaped'));
  assert.throws(
    () => _internal.resolveProjectPath(root, './escaped', 'embeddedBundlesPath', 'directory'),
    /resolves outside/
  );
});

test('requires exactly one V2 baseline tree and key, without legacy duplicate resources', () => {
  assert.throws(
    () => _internal.validateV2Options({ embeddedBundlesPath: './generated' }),
    /configured together/
  );
  assert.throws(
    () =>
      _internal.validateV2Options({
        embeddedBundlesPath: './generated',
        publicKeyPath: './keys/updates.public.pem',
        bundledResources: ['./assets/static.lynx'],
      }),
    /cannot be combined/
  );
  assert.deepEqual(
    _internal.validateV2Options({
      embeddedBundlesPath: './generated',
      publicKeyPath: './keys/updates.public.pem',
    }),
    {
      embeddedBundlesPath: './generated',
      publicKeyPath: './keys/updates.public.pem',
      deliveryEndpoints: undefined,
    }
  );
});

test('validates canonical build-time deployment URLs against the embedded registry', () => {
  const options = {
    deliveryEndpoints: {
      shopping: 'https://delivery.example.com/v1/deploy/shopping',
    },
  };
  assert.deepEqual(_internal.normalizeDeliveryEndpoints(options.deliveryEndpoints, ['shopping']), {
    shopping: 'https://delivery.example.com/v1/deploy/shopping',
  });
  assert.deepEqual(
    _internal.normalizeDeliveryEndpoints(
      { shopping: 'https://delivery.example.com/v1/shop/shopping' },
      ['shopping']
    ),
    { shopping: 'https://delivery.example.com/v1/shop/shopping' }
  );
  assert.throws(
    () =>
      _internal.normalizeDeliveryEndpoints(
        { shopping: 'https://delivery.example.com/v1/deploy/other' },
        ['shopping']
      ),
    /canonical deployment URL/
  );
  assert.throws(
    () =>
      _internal.normalizeDeliveryEndpoints(
        { shopping: 'https://delivery.example.com/v1/shop/other' },
        ['shopping']
      ),
    /canonical deployment URL/
  );
  assert.throws(
    () =>
      _internal.normalizeDeliveryEndpoints(
        { unknown: 'https://delivery.example.com/v1/deploy/unknown' },
        ['shopping']
      ),
    /not in the embedded registry/
  );
});

test('materializes the shared baseline and emits the prepared iOS runtime into Info.plist', () => {
  const { root } = makeTemporaryEmbeddedTree();
  const keyDirectory = path.join(root, 'keys');
  fs.mkdirSync(keyDirectory);
  fs.copyFileSync(
    path.join(fixtureRoot, 'crypto-development/updates.public.pem'),
    path.join(keyDirectory, 'release.public.pem')
  );
  const nativeRoot = path.join(root, 'ios');
  const destination = _internal.materializeV2Resources({
    projectRoot: root,
    platformProjectRoot: nativeRoot,
    nativeProjectName: 'Example',
    options: {
      embeddedBundlesPath: './generated/expo-lynx/embedded',
      publicKeyPath: './keys/release.public.pem',
    },
  });
  assert.equal(destination, path.join(nativeRoot, 'Example', _internal.EMBEDDED_DIRECTORY));
  assert.equal(
    fs.readFileSync(path.join(destination, 'shopping/main.lynx.bundle'), 'utf8'),
    'mini-app'
  );
  assert.equal(fs.existsSync(path.join(destination, 'updates.public.pem')), false);
  assert.equal(fs.existsSync(path.join(destination, 'trust.json')), false);
  assert.equal(fs.existsSync(path.join(destination, 'updates.private.pem')), false);

  const featureDeclaration = path.join(root, 'generated/expo-lynx/lynx-features.d.ts');
  assert.equal(
    fs.readFileSync(featureDeclaration, 'utf8'),
    `// This file is generated by expo-lynx-view during Expo prebuild. Do not edit.\n` +
      `// It is derived from the validated embedded registry, not from network content.\n` +
      `import 'expo-lynx-view';\n\n` +
      `declare module 'expo-lynx-view' {\n` +
      `  interface ExpoLynxFeatureMap {\n` +
      `    readonly "shopping": true;\n` +
      `  }\n` +
      `}\n\n` +
      `export {};\n`
  );

  const infoPlist = _internal.applyV2InfoPlist({}, root, {
    embeddedBundlesPath: './generated/expo-lynx/embedded',
    publicKeyPath: './keys/release.public.pem',
    deliveryEndpoints: {
      shopping: 'https://delivery.example.com/v1/deploy/shopping',
    },
  });
  assert.match(infoPlist[_internal.INFO_PLIST_PUBLIC_KEY], /BEGIN PUBLIC KEY/);
  assert.match(infoPlist[_internal.INFO_PLIST_PUBLIC_KEY_FINGERPRINT], /^[A-Za-z0-9_-]{43}$/);
  assert.equal(infoPlist[_internal.INFO_PLIST_RUNTIME_VERSION], 'ios:expo-57');
  assert.deepEqual(infoPlist[_internal.INFO_PLIST_DELIVERY_ENDPOINTS], {
    shopping: 'https://delivery.example.com/v1/deploy/shopping',
  });
});

test('materializes the same V2 runtime, endpoints, and public key into Android assets', () => {
  const { root } = makeTemporaryEmbeddedTree();
  const keyDirectory = path.join(root, 'keys');
  fs.mkdirSync(keyDirectory);
  fs.copyFileSync(
    path.join(fixtureRoot, 'crypto-development/updates.public.pem'),
    path.join(keyDirectory, 'release.public.pem')
  );
  const result = _internal.materializeV2AndroidResources({
    projectRoot: root,
    options: {
      embeddedBundlesPath: './generated/expo-lynx/embedded',
      publicKeyPath: './keys/release.public.pem',
      deliveryEndpoints: { shopping: 'https://delivery.example.com/v1/shop/shopping' },
    },
  });
  assert.equal(
    fs.readFileSync(path.join(result.embeddedDestination, 'shopping/main.lynx.bundle'), 'utf8'),
    'mini-app'
  );
  assert.deepEqual(JSON.parse(fs.readFileSync(result.configurationPath, 'utf8')), {
    schemaVersion: 1,
    runtimeVersion: 'android:expo-57',
    deliveryEndpoints: { shopping: 'https://delivery.example.com/v1/shop/shopping' },
    publicKey: _internal.normalizePublicKey(path.join(keyDirectory, 'release.public.pem')).pem,
  });
});

test('rejects native prebuild when that platform was not prepared', () => {
  const { root, embedded } = makeTemporaryEmbeddedTree();
  const registryPath = path.join(embedded, 'registry.json');
  const registry = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
  delete registry.runtimes.android;
  fs.writeFileSync(registryPath, JSON.stringify(registry));
  const keyDirectory = path.join(root, 'keys');
  fs.mkdirSync(keyDirectory);
  fs.copyFileSync(
    path.join(fixtureRoot, 'crypto-development/updates.public.pem'),
    path.join(keyDirectory, 'release.public.pem')
  );
  assert.throws(
    () => _internal.materializeV2AndroidResources({
      projectRoot: root,
      options: {
        embeddedBundlesPath: './generated/expo-lynx/embedded',
        publicKeyPath: './keys/release.public.pem',
        deliveryEndpoints: { shopping: 'https://delivery.example.com/v1/shop/shopping' },
      },
    }),
    /prepared android runtime/
  );
});

test('reuses the existing Xcode folder reference on repeated prebuilds', () => {
  const xcodePath = `Example/${_internal.EMBEDDED_DIRECTORY}`;
  const reference = {
    path: `"${xcodePath}"`,
    explicitFileType: 'folder',
    fileEncoding: 4,
  };
  const project = {
    hasFile(candidate) {
      return candidate === xcodePath;
    },
    pbxFileReferenceSection() {
      return { reference };
    },
  };
  const result = _internal.addResource(project, 'Example', xcodePath, true);
  assert.equal(result, project);
  assert.equal(reference.lastKnownFileType, 'folder');
  assert.equal('explicitFileType' in reference, false);
  assert.equal('fileEncoding' in reference, false);
});
