const {
  createRunOncePlugin,
  IOSConfig,
  withDangerousMod,
  withPodfile,
  withXcodeProject,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const packageJSON = require('./package.json');

const generatedMarker = '# @generated by expo-lynx';

const rubyHelper = `${generatedMarker}
def expo_lynx_post_install(installer)
  lynx_targets = installer.pods_project.targets.select do |target|
    ['Lynx', 'BaseDevtool', 'LynxDevtool', 'LynxService'].include?(target.name)
  end
  return if lynx_targets.empty?

  disabled_warnings = [
    '-Wno-error',
    '-Wno-c99-designator',
    '-Wno-deprecated-declarations',
    '-Wno-deprecated-implementations',
  ]

  lynx_targets.each do |target|
    target.build_configurations.each do |config|
      # React Native sets strict c++20 for all Pods. Lynx 4 uses GNU typeof in .mm files.
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++20'
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      # Xcode 26's generated Pod settings disable Obj-C weak references, but
      # Lynx's DevTool and reload helpers use __weak/__strong extensively.
      config.build_settings['CLANG_ENABLE_OBJC_WEAK'] = 'YES'

      ['OTHER_CPLUSPLUSFLAGS', 'OTHER_CFLAGS'].each do |key|
        flags = config.build_settings[key] || ['$(inherited)']
        flags = [flags] unless flags.is_a?(Array)
        config.build_settings[key] = (flags + disabled_warnings).uniq
      end
    end
  end
end
`;

function findClosingParenthesis(contents, openingIndex) {
  let depth = 0;
  let quote = null;
  let escaped = false;

  for (let index = openingIndex; index < contents.length; index += 1) {
    const character = contents[index];

    if (quote) {
      if (escaped) {
        escaped = false;
      } else if (character === '\\') {
        escaped = true;
      } else if (character === quote) {
        quote = null;
      }
      continue;
    }

    if (character === "'" || character === '"') {
      quote = character;
    } else if (character === '(') {
      depth += 1;
    } else if (character === ')') {
      depth -= 1;
      if (depth === 0) {
        return index;
      }
    }
  }

  return -1;
}

function addExpoLynxPostInstall(contents) {
  if (contents.includes(generatedMarker)) {
    return contents;
  }

  const functionIndex = contents.indexOf('react_native_post_install(');
  if (functionIndex === -1) {
    throw new Error('expo-lynx could not find react_native_post_install in the iOS Podfile.');
  }

  const openingIndex = contents.indexOf('(', functionIndex);
  const closingIndex = findClosingParenthesis(contents, openingIndex);
  if (closingIndex === -1) {
    throw new Error('expo-lynx could not parse the react_native_post_install call.');
  }

  const call = '\n\n    expo_lynx_post_install(installer)';
  return `${rubyHelper}\n${contents.slice(0, closingIndex + 1)}${call}${contents.slice(closingIndex + 1)}`;
}

function copyBundledResource(sourcePath, destinationPath) {
  if (fs.statSync(sourcePath).isDirectory()) {
    fs.cpSync(sourcePath, destinationPath, { recursive: true, force: true });
    return;
  }

  fs.copyFileSync(sourcePath, destinationPath);
}

function markResourceDirectoryAsFolder(project, xcodePath) {
  const normalizedPath = xcodePath.replace(/\\/g, '/');
  const references = project.pbxFileReferenceSection();

  for (const [key, reference] of Object.entries(references)) {
    if (key.endsWith('_comment') || !reference || typeof reference !== 'object') {
      continue;
    }

    const referencePath = String(reference.path || '').replace(/^"|"$/g, '');
    if (referencePath !== normalizedPath) {
      continue;
    }

    reference.lastKnownFileType = 'folder';
    delete reference.explicitFileType;
    delete reference.fileEncoding;
    return;
  }

  throw new Error(`expo-lynx could not mark the iOS resource directory as a folder: ${xcodePath}`);
}

function withBundledResources(config, bundledResources) {
  if (!bundledResources.length) {
    return config;
  }

  config = withXcodeProject(config, (projectConfig) => {
    const { platformProjectRoot, projectName, projectRoot } = projectConfig.modRequest;
    const nativeProjectName = projectName || IOSConfig.XcodeUtils.getProjectName(projectRoot);
    const nativeSourceRoot = path.join(platformProjectRoot, nativeProjectName);

    for (const resourcePath of bundledResources) {
      const sourcePath = path.resolve(projectRoot, resourcePath);
      if (!fs.existsSync(sourcePath)) {
        throw new Error(`expo-lynx bundled resource does not exist: ${resourcePath}`);
      }

      const filename = path.basename(sourcePath);
      const destinationPath = path.join(nativeSourceRoot, filename);
      const xcodePath = `${nativeProjectName}/${filename}`;
      const isDirectory = fs.statSync(sourcePath).isDirectory();

      copyBundledResource(sourcePath, destinationPath);

      if (!projectConfig.modResults.hasFile(xcodePath)) {
        projectConfig.modResults = IOSConfig.XcodeUtils.addResourceFileToGroup({
          filepath: xcodePath,
          groupName: nativeProjectName,
          isBuildFile: true,
          project: projectConfig.modResults,
        });
      }

      if (isDirectory) {
        // A blue folder reference makes Xcode preserve the relative paths
        // instead of flattening every sidecar file into the app root.
        markResourceDirectoryAsFolder(projectConfig.modResults, xcodePath);
      }
    }

    return projectConfig;
  });

  // ponytail: same copies for Android — drop each bundled resource into
  // android/app/src/main/assets so the host's assets.open(uri) resolves.
  // Static bundle loading failed with code 102 / sub_code 10203 because
  // this copy was missing on Android.
  return withDangerousMod(config, [
    'android',
    (androidConfig) => {
      const { projectRoot } = androidConfig.modRequest;
      const androidAssetsDir = path.join(projectRoot, 'android', 'app', 'src', 'main', 'assets');
      fs.mkdirSync(androidAssetsDir, { recursive: true });

      for (const resourcePath of bundledResources) {
        const sourcePath = path.resolve(projectRoot, resourcePath);
        if (!fs.existsSync(sourcePath)) {
          throw new Error(`expo-lynx bundled resource does not exist: ${resourcePath}`);
        }
        const filename = path.basename(sourcePath);
        copyBundledResource(sourcePath, path.join(androidAssetsDir, filename));
      }

      return androidConfig;
    },
  ]);
}

const withExpoLynx = (config, options = {}) => {
  const bundledResources = options.bundledResources || [];

  config = withPodfile(config, (podfileConfig) => {
    podfileConfig.modResults.contents = addExpoLynxPostInstall(podfileConfig.modResults.contents);
    return podfileConfig;
  });

  return withBundledResources(config, bundledResources);
};

module.exports = createRunOncePlugin(withExpoLynx, packageJSON.name, packageJSON.version);
