const crypto = require('crypto');
const {
  createRunOncePlugin,
  IOSConfig,
  withDangerousMod,
  withInfoPlist,
  withPodfile,
  withXcodeProject,
} = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

// `mergeContents` isn't part of expo/config-plugins' public API, so resolve
// it through expo's own dependency tree rather than a bare deep import,
// which would only happen to work if the consuming app's package manager
// hoists @expo/config-plugins to somewhere require can see from here.
const { mergeContents, removeContents } = require(
  require.resolve('@expo/config-plugins/build/utils/generateCode', {
    paths: [path.dirname(require.resolve('expo/package.json'))],
  })
);

const packageJSON = require('./package.json');

const generatedMarker = '# @generated by expo-lynx-view';
const legacyGeneratedMarker = '# @generated by expo-lynx';
const DEVTOOL_POD_TAG = 'expo-lynx-view-devtool';
const SPECS_SOURCE_TAG = 'expo-lynx-view-specs-source';
const LYNX_PRECOMPILED_POD_TAG = 'expo-lynx-view-precompiled-lynx';
const LYNX_SPECS_REPO_URL = 'https://github.com/lynx-family/Specs.git';
// Keep in sync with the Lynx/PrimJS/LynxService pins in ios/ExpoLynx.podspec.
const IOS_LYNX_VERSION = '4.1.0';
// DebugRouter doesn't move in lockstep with the Lynx version (see the doc
// link in addExpoLynxDevtoolPod).
const DEBUG_ROUTER_VERSION = '5.0.15';
const EMBEDDED_DIRECTORY = 'ExpoLynxEmbedded.bundle';
const INFO_PLIST_PUBLIC_KEY = 'ExpoLynxPublicKey';
const INFO_PLIST_PUBLIC_KEY_FINGERPRINT = 'ExpoLynxPublicKeyFingerprint';
const INFO_PLIST_DELIVERY_ENDPOINTS = 'ExpoLynxDeliveryEndpoints';
const INFO_PLIST_RUNTIME_VERSION = 'ExpoLynxRuntimeVersion';
const ANDROID_EMBEDDED_DIRECTORY = 'expo-lynx-embedded';
const ANDROID_DELIVERY_CONFIGURATION = 'expo-lynx-delivery.json';
const FEATURE_ID = /^[a-z][a-z0-9-]{0,63}$/;
const SHA_256 = /^[a-f0-9]{64}$/;
const MAX_PUBLIC_KEY_BYTES = 16 * 1024;
const MAX_ENTRIES = 4096;
const MAX_SINGLE_ENTRY_BYTES = 64 * 1024 * 1024;
const MAX_UNCOMPRESSED_BYTES = 256 * 1024 * 1024;

const rubyHelper = `${generatedMarker}
def expo_lynx_post_install(installer)
  # The precompiled Lynx.xcframework (devTool: false) bakes in its own
  # Modules/module.modulemap from when it was built, so Xcode treats it as a
  # framework module and explicit-modules-builds it. Its umbrella header
  # pulls in LynxServiceAPI's headers, which aren't themselves built as a
  # module (plain flat pod headers) — under strict modules this is
  # "include of non-modular header inside framework module ... [-Werror,
  # -Wnon-modular-include-in-framework-module]", which aborts the whole
  # module build before any of our other per-target settings even apply.
  # Confirmed with a real \`xcodebuild\`: PrecompileModule for Lynx failed
  # with exactly this error until this setting was added project-wide (the
  # module can be triggered by whichever target imports Lynx first, not
  # necessarily one of the named lynx_targets below).
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end

  # react_native_post_install (called before this hook, from the Podfile's
  # own post_install block) forces CLANG_CXX_LANGUAGE_STANDARD = 'c++20'
  # (strict ISO, not GNU) across every target in the Pods project, clobbering
  # each of these pods' own xcconfig-declared standard. Strict C++20 breaks
  # Clang's \`typeof\` GNU extension in ObjC++ ARC code — XElement's
  # LynxSVGRenderer.mm uses \`__weak typeof(self) weakSelf = self;\`, which
  # then fails to parse with "expected unqualified-id". \`gnu++20\` doesn't
  # have this problem. Confirmed by isolating the exact failing compiler
  # invocation and re-running it with -std=gnu++20 vs -std=c++20.
  lynx_targets = installer.pods_project.targets.select do |target|
    ['Lynx', 'BaseDevtool', 'LynxDevtool', 'LynxService', 'XElement'].include?(target.name)
  end

  disabled_warnings = [
    '-Wno-error',
    '-Wno-c99-designator',
    '-Wno-deprecated-declarations',
    '-Wno-deprecated-implementations',
  ]

  lynx_targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++20'
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      config.build_settings['CLANG_ENABLE_OBJC_WEAK'] = 'YES'

      ['OTHER_CPLUSPLUSFLAGS', 'OTHER_CFLAGS'].each do |key|
        flags = config.build_settings[key] || ['$(inherited)']
        flags = [flags] unless flags.is_a?(Array)
        config.build_settings[key] = (flags + disabled_warnings).uniq
      end
    end
  end

  # ServalSVG and ServalMarkdown (serval-kit, vendored via XElement) each do a
  # plain \`#include "stdlib.h"\` / \`#include "stdio.h"\`. Xcode's per-target
  # header map indexes every pod's headers by bare filename
  # case-insensitively project-wide, and ReactNativeDependencies bundles
  # folly/portability/{Stdlib,Stdio}.h — the quoted include resolves to one
  # of those instead of the real system header, producing a bogus
  # "'folly/CPortability.h' file not found" (or 'cstdio'/'cstdlib') from
  # inside Folly's own shim. Disabling the header map forces a real directory
  # search, which finds the actual system header first. If a future
  # serval-kit/XElement pod hits the same error, add its target name here —
  # grep the Pods/ source for a matching quoted libc include to confirm it's
  # the same collision before doing so.
  header_map_collision_targets = installer.pods_project.targets.select do |target|
    ['ServalSVG', 'ServalMarkdown'].include?(target.name)
  end
  header_map_collision_targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['USE_HEADERMAP'] = 'NO'
    end
  end

  internal_release_conditions = [
    'LYNX_ALLOW_LOCAL_MANAGED_RELEASE',
    'LYNX_IFR_METRICS',
  ]
  release_conditions = []
  release_conditions << 'LYNX_ALLOW_LOCAL_MANAGED_RELEASE' if ENV['LYNX_ALLOW_LOCAL_MANAGED_RELEASE'] == '1'
  release_conditions << 'LYNX_IFR_METRICS' if ENV['LYNX_IFR_METRICS'] == '1'

  expo_lynx_target = installer.pods_project.targets.find do |target|
    target.name == 'ExpoLynx'
  end

  if expo_lynx_target
    expo_lynx_target.build_configurations.each do |config|
      next unless config.name == 'Release'

      conditions = config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] || ['$(inherited)']
      conditions = [conditions] unless conditions.is_a?(Array)
      conditions = conditions.reject { |condition| internal_release_conditions.include?(condition) }
      config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = (
        conditions + release_conditions
      ).uniq
    end
  end
end
`;

function findClosingParenthesis(contents, openingIndex) {
  let depth = 0;
  let quote = null;
  let escaped = false;
  for (let index = openingIndex; index < contents.length; index += 1) {
    const character = contents[index];
    if (quote) {
      if (escaped) escaped = false;
      else if (character === '\\') escaped = true;
      else if (character === quote) quote = null;
      continue;
    }
    if (character === "'" || character === '"') quote = character;
    else if (character === '(') depth += 1;
    else if (character === ')') {
      depth -= 1;
      if (depth === 0) return index;
    }
  }
  return -1;
}

function addExpoLynxPostInstall(contents) {
  const markerIndex = [generatedMarker, legacyGeneratedMarker]
    .map((marker) => contents.indexOf(marker))
    .find((index) => index !== -1);
  if (markerIndex !== undefined) {
    const requireIndex = contents.indexOf('\nrequire ', markerIndex);
    if (requireIndex !== -1) return `${rubyHelper}${contents.slice(requireIndex + 1)}`;
  }
  const functionIndex = contents.indexOf('react_native_post_install(');
  if (functionIndex === -1)
    throw new Error('expo-lynx-view could not find react_native_post_install in the iOS Podfile.');
  const openingIndex = contents.indexOf('(', functionIndex);
  const closingIndex = findClosingParenthesis(contents, openingIndex);
  if (closingIndex === -1)
    throw new Error('expo-lynx-view could not parse the react_native_post_install call.');
  return `${rubyHelper}\n${contents.slice(0, closingIndex + 1)}\n\n    expo_lynx_post_install(installer)${contents.slice(closingIndex + 1)}`;
}

function addExpoLynxSpecsSource(contents) {
  // Lynx/PrimJS/LynxService/XElement/DebugRouter/LynxDevtool/BaseDevtool are
  // only published on the lynx-family Specs repo, not CocoaPods trunk (trunk
  // mirrors some Lynx pods, but not every version — notably not every stable
  // 4.x). A Podfile with no explicit `source` line falls back to trunk only
  // (see CocoaPods' Installer::Analyzer#sources), so without this line
  // CocoaPods silently can't find pods pinned to a version trunk lacks. This
  // must be generated by the plugin, not hand-edited into the native
  // project — a gitignored `ios/Podfile` is rebuilt from scratch on every
  // `expo prebuild --clean` and a manual edit will not survive that.
  let result;
  try {
    result = mergeContents({
      tag: SPECS_SOURCE_TAG,
      src: contents,
      newSrc: `source 'https://cdn.cocoapods.org/'\nsource '${LYNX_SPECS_REPO_URL}'`,
      anchor: /^platform :ios/m,
      offset: 0,
      comment: '#',
    });
  } catch (error) {
    if (error.code === 'ERR_NO_MATCH')
      throw new Error('expo-lynx-view could not find `platform :ios` in the iOS Podfile.');
    throw error;
  }
  return result.contents;
}

function addExpoLynxPrecompiledPod(contents) {
  // ExpoLynx.podspec depends on the bare `Lynx` pod name (via `Lynx/Framework`),
  // which CocoaPods would otherwise resolve from the lynx-family Specs repo as
  // full C++ SOURCE (slow to compile, and it fights newer Xcode's -Werror).
  // This :path override redirects every `Lynx` requirement in the whole
  // graph to the prebuilt ios/Precompiled/Lynx.xcframework instead. It must
  // be generated by the plugin, not hand-edited into the native project —
  // same reasoning as addExpoLynxSpecsSource: a gitignored `ios/Podfile` is
  // rebuilt from scratch on `expo prebuild --clean` and won't keep a manual
  // edit. Losing this line silently falls back to the source pod, which then
  // fights the vendored xcframework for the same Objective-C class names
  // (e.g. `LynxPerformanceController`) — a duplicate-interface build error,
  // not a missing-pod error, so it's easy to miss the real cause.
  //
  // Only called when devTool is off (see withExpoLynx) — LynxDevtool is
  // built from source and reaches into Lynx's internal C++ headers via
  // nested quoted includes (e.g. `#include "base/include/value/base_value.h"`).
  // A compiled .framework flattens every header into one Headers/
  // directory, losing that nested path, so those includes can't resolve
  // against the precompiled xcframework no matter what search paths are
  // added — confirmed with a real `xcodebuild`: LynxDevtool's
  // white_board_inspector_impl.cc failed with "'base/include/value/base_value.h'
  // file not found" even though the file exists (flattened) in the
  // xcframework's PrivateHeaders. Letting Lynx resolve from source instead
  // whenever devTool is on gives LynxDevtool the real, nested source tree it
  // expects — slower Debug+devTool builds, but Release and devTool:false
  // builds still get the fast precompiled path.
  const precompiledPath = path.join(__dirname, 'ios', 'Precompiled');
  if (!fs.existsSync(path.join(precompiledPath, 'Lynx.podspec'))) {
    throw new Error(
      `expo-lynx-view could not find a precompiled Lynx at ${precompiledPath}. ` +
        'Build it with packages/expo-lynx/precompile-host/bump-lynx-version.sh <version>, ' +
        'or copy a prebuilt one from the codex/precompile-lynx branch.'
    );
  }
  let result;
  try {
    result = mergeContents({
      tag: LYNX_PRECOMPILED_POD_TAG,
      src: contents,
      newSrc: `  pod 'Lynx', :path => '${precompiledPath.replace(/'/g, "\\'")}'`,
      anchor: /use_expo_modules!/,
      offset: 0,
      comment: '#',
    });
  } catch (error) {
    if (error.code === 'ERR_NO_MATCH')
      throw new Error('expo-lynx-view could not find use_expo_modules! in the iOS Podfile.');
    throw error;
  }
  return result.contents;
}

function removeExpoLynxPrecompiledPod(contents) {
  // Mirrors addExpoLynxDevtoolPod's toggle handling: called when devTool is
  // on, so a prior devTool:false prebuild's :path override doesn't linger
  // and fight the source-resolved Lynx that LynxDevtool needs.
  return removeContents({ tag: LYNX_PRECOMPILED_POD_TAG, src: contents }).contents;
}

function addExpoLynxDevtoolPod(contents) {
  // LynxService/Devtool pulls in LynxDevtool, BaseDevtool, and DebugRouter
  // transitively. `:configurations` on a Podfile pod line does NOT propagate
  // to that pod's own dependencies — CocoaPods only restricts the exact pod
  // it's attached to, so scoping just LynxService/Devtool still links
  // LynxDevtool/BaseDevtool/DebugRouter into Release. Each has to be scoped
  // explicitly. `:configurations` only works here, in the app's Podfile — a
  // podspec's `s.dependency` silently ignores it and would still link
  // DebugRouter into Release hosts.
  let result;
  try {
    result = mergeContents({
      tag: DEVTOOL_POD_TAG,
      src: contents,
      newSrc: [
        `  pod 'LynxService/Devtool', '${IOS_LYNX_VERSION}', :configurations => ['Debug']`,
        `  pod 'LynxDevtool', '${IOS_LYNX_VERSION}', :configurations => ['Debug']`,
        `  pod 'BaseDevtool', '${IOS_LYNX_VERSION}', :configurations => ['Debug']`,
        `  pod 'DebugRouter', '${DEBUG_ROUTER_VERSION}', :configurations => ['Debug']`,
      ].join('\n'),
      anchor: /use_expo_modules!/,
      offset: 0,
      comment: '#',
    });
  } catch (error) {
    if (error.code === 'ERR_NO_MATCH')
      throw new Error('expo-lynx-view could not find use_expo_modules! in the iOS Podfile.');
    throw error;
  }
  return result.contents;
}

function removeExpoLynxDevtoolPod(contents) {
  // Mirrors addExpoLynxDevtoolPod so a prebuild that flips `devTool` from
  // true to false (without a clean) strips a previously injected line
  // instead of leaving it stale in the regenerated Podfile.
  return removeContents({ tag: DEVTOOL_POD_TAG, src: contents }).contents;
}

function resolveDevToolOption(options) {
  if (options.devTool === undefined) return true;
  if (typeof options.devTool !== 'boolean')
    throw new Error('expo-lynx-view devTool must be a boolean.');
  return options.devTool;
}

function isPlainObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function assertKnownKeys(value, allowed, label) {
  if (!isPlainObject(value)) throw new Error(`expo-lynx-view ${label} must be an object.`);
  for (const key of Object.keys(value)) {
    if (!allowed.has(key))
      throw new Error(`expo-lynx-view ${label} contains an unsupported field: ${key}`);
  }
}

function assertRelativePath(value, optionName) {
  if (typeof value !== 'string' || !value.trim() || value.includes('\0')) {
    throw new Error(`expo-lynx-view ${optionName} must be one non-empty relative path.`);
  }
  if (path.isAbsolute(value) || value.startsWith('//') || /^[a-z][a-z0-9+.-]*:/i.test(value)) {
    throw new Error(`expo-lynx-view ${optionName} must be relative to the Expo app project root.`);
  }
  return value;
}

function isContained(root, candidate) {
  const relativePath = path.relative(root, candidate);
  return (
    relativePath === '' ||
    (!relativePath.startsWith(`..${path.sep}`) &&
      relativePath !== '..' &&
      !path.isAbsolute(relativePath))
  );
}

function resolveProjectPath(projectRoot, configuredPath, optionName, kind) {
  const relativePath = assertRelativePath(configuredPath, optionName);
  const lexical = path.resolve(projectRoot, relativePath);
  if (!isContained(projectRoot, lexical))
    throw new Error(`expo-lynx-view ${optionName} escapes the Expo app project root.`);
  if (!fs.existsSync(lexical))
    throw new Error(`expo-lynx-view ${optionName} does not exist: ${relativePath}`);
  // Resolve a symlink before checking its kind. An in-project symlink remains
  // valid, but the realpath containment check below rejects an escaped target.
  const stat = fs.statSync(lexical);
  if ((kind === 'file' && !stat.isFile()) || (kind === 'directory' && !stat.isDirectory())) {
    throw new Error(`expo-lynx-view ${optionName} must be a ${kind}.`);
  }
  const realProjectRoot = fs.realpathSync(projectRoot);
  const realPath = fs.realpathSync(lexical);
  if (!isContained(realProjectRoot, realPath))
    throw new Error(`expo-lynx-view ${optionName} resolves outside the Expo app project root.`);
  return realPath;
}

function normalizePublicKey(sourcePath) {
  if (!path.basename(sourcePath).endsWith('.public.pem')) {
    throw new Error('expo-lynx-view publicKeyPath must end with .public.pem.');
  }
  const size = fs.statSync(sourcePath).size;
  if (size <= 0 || size > MAX_PUBLIC_KEY_BYTES)
    throw new Error('expo-lynx-view publicKeyPath must be a UTF-8 file no larger than 16 KiB.');
  const raw = fs.readFileSync(sourcePath);
  let pem;
  try {
    pem = new TextDecoder('utf-8', { fatal: true }).decode(raw);
  } catch {
    throw new Error('expo-lynx-view publicKeyPath must be valid UTF-8.');
  }
  const normalized = `${pem.replace(/\r\n?/g, '\n').trimEnd()}\n`;
  if (/PRIVATE KEY|BEGIN CERTIFICATE|BEGIN RSA PUBLIC KEY/.test(normalized)) {
    throw new Error(
      'expo-lynx-view publicKeyPath must contain one SPKI public key, never a private key or certificate.'
    );
  }
  const blocks = normalized.match(/-----BEGIN [^-]+-----[\s\S]*?-----END [^-]+-----/g) ?? [];
  if (blocks.length !== 1 || blocks[0] !== normalized.trim())
    throw new Error('expo-lynx-view publicKeyPath must contain exactly one PEM block.');
  if (
    !normalized.startsWith('-----BEGIN PUBLIC KEY-----\n') ||
    !normalized.endsWith('-----END PUBLIC KEY-----\n')
  ) {
    throw new Error('expo-lynx-view publicKeyPath must be a SubjectPublicKeyInfo PEM public key.');
  }
  let key;
  try {
    key = crypto.createPublicKey(normalized);
  } catch {
    throw new Error('expo-lynx-view publicKeyPath is not a parseable SPKI public key.');
  }
  const details = key.asymmetricKeyDetails;
  if (
    key.asymmetricKeyType !== 'rsa' ||
    !details ||
    details.modulusLength < 3072 ||
    Number(details.publicExponent) !== 65537
  ) {
    throw new Error(
      'expo-lynx-view publicKeyPath must be RSA with a 3072-bit-or-larger modulus and exponent 65537.'
    );
  }
  const der = key.export({ type: 'spki', format: 'der' });
  return {
    pem: normalized,
    fingerprint: crypto.createHash('sha256').update(der).digest('base64url'),
  };
}

function assertFeature(value, label) {
  if (typeof value !== 'string' || !FEATURE_ID.test(value))
    throw new Error(`expo-lynx-view ${label} has an invalid feature key.`);
}

function normalizeDeliveryEndpoints(value, allowedFeatures) {
  if (value === undefined) return {};
  if (!isPlainObject(value)) throw new Error('expo-lynx-view deliveryEndpoints must be an object.');
  const normalized = {};
  for (const [feature, endpoint] of Object.entries(value)) {
    assertFeature(feature, 'deliveryEndpoints');
    if (allowedFeatures && !allowedFeatures.includes(feature)) {
      throw new Error(
        `expo-lynx-view deliveryEndpoints feature is not in the embedded registry: ${feature}`
      );
    }
    if (typeof endpoint !== 'string' || !endpoint.trim()) {
      throw new Error(`expo-lynx-view deliveryEndpoints.${feature} must be a non-empty URL.`);
    }
    let url;
    try {
      url = new URL(endpoint);
    } catch {
      throw new Error(`expo-lynx-view deliveryEndpoints.${feature} must be an HTTP(S) URL.`);
    }
    const scopedRoute = url.pathname.match(
      /^\/v1\/([a-z][a-z0-9-]{0,63})\/([a-z][a-z0-9-]{0,63})$/
    );
    if (
      (url.protocol !== 'https:' && url.protocol !== 'http:') ||
      !url.hostname ||
      url.username ||
      url.password ||
      url.search ||
      url.hash ||
      (url.pathname !== `/v1/deploy/${feature}` && scopedRoute?.[2] !== feature)
    ) {
      throw new Error(
        `expo-lynx-view deliveryEndpoints.${feature} must be a credential-free canonical deployment URL.`
      );
    }
    normalized[feature] = url.toString();
  }
  return normalized;
}

function assertSafeRelativePath(value, label) {
  if (
    typeof value !== 'string' ||
    !value ||
    value.startsWith('/') ||
    value.includes('\\') ||
    value.includes('\0')
  ) {
    throw new Error(`expo-lynx-view ${label} has an unsafe path.`);
  }
  const parts = value.split('/');
  if (parts.length > 16 || parts.some((part) => !part || part === '.' || part === '..'))
    throw new Error(`expo-lynx-view ${label} has an unsafe path.`);
}

function assertHash(value, label) {
  if (typeof value !== 'string' || !SHA_256.test(value))
    throw new Error(`expo-lynx-view ${label} has an invalid SHA-256.`);
}

function parseJSONFile(filePath, label) {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch {
    throw new Error(`expo-lynx-view ${label} is not valid JSON.`);
  }
}

function resolveEmbeddedPath(root, relativePath, label) {
  assertSafeRelativePath(relativePath, label);
  const absolute = path.resolve(root, relativePath);
  if (!isContained(root, absolute))
    throw new Error(`expo-lynx-view ${label} escapes the embedded bundle root.`);
  if (!fs.existsSync(absolute) || !fs.lstatSync(absolute).isFile())
    throw new Error(`expo-lynx-view ${label} is missing or not a regular file.`);
  const realRoot = fs.realpathSync(root);
  const realPath = fs.realpathSync(absolute);
  if (!isContained(realRoot, realPath))
    throw new Error(`expo-lynx-view ${label} resolves outside the embedded bundle root.`);
  return realPath;
}

function runtimeFiles(featureDirectory) {
  const files = [];
  const walk = (directory, prefix = '') => {
    for (const entry of fs
      .readdirSync(directory, { withFileTypes: true })
      .sort((a, b) => a.name.localeCompare(b.name))) {
      const absolute = path.join(directory, entry.name);
      const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isSymbolicLink() || entry.name.startsWith('.'))
        throw new Error(
          `expo-lynx-view embedded output contains a forbidden entry: ${relativePath}`
        );
      if (entry.isDirectory()) walk(absolute, relativePath);
      else if (entry.isFile()) {
        if (relativePath !== 'baseline.json') {
          assertSafeRelativePath(relativePath, `embedded output ${relativePath}`);
          files.push({
            path: relativePath,
            bytes: fs.statSync(absolute).size,
            sha256: crypto.createHash('sha256').update(fs.readFileSync(absolute)).digest('hex'),
          });
        }
      } else
        throw new Error(
          `expo-lynx-view embedded output contains an unsupported entry: ${relativePath}`
        );
    }
  };
  walk(featureDirectory);
  return files;
}

function validateEmbeddedBundles(sourcePath, platform) {
  const registryPath = resolveEmbeddedPath(sourcePath, 'registry.json', 'embedded registry');
  const registry = parseJSONFile(registryPath, 'embedded registry');
  if (
    !isPlainObject(registry) ||
    registry.schemaVersion !== 2 ||
    !isPlainObject(registry.features) ||
    !isPlainObject(registry.runtimes)
  ) {
    throw new Error('expo-lynx-view embedded registry is malformed.');
  }
  const features = Object.keys(registry.features).sort();
  if (features.length === 0)
    throw new Error('expo-lynx-view embedded registry must declare at least one feature.');
  const expectedTopLevel = new Set(['registry.json', ...features]);
  for (const entry of fs.readdirSync(sourcePath, { withFileTypes: true })) {
    if (
      !expectedTopLevel.has(entry.name) ||
      entry.isSymbolicLink() ||
      (entry.name !== 'registry.json' && !entry.isDirectory())
    ) {
      throw new Error(
        `expo-lynx-view embedded output has an unexpected top-level entry: ${entry.name}`
      );
    }
  }
  for (const feature of features) {
    assertFeature(feature, 'embedded registry');
    const registryEntry = registry.features[feature];
    if (
      !isPlainObject(registryEntry) ||
      registryEntry.baseline !== `${feature}/baseline.json` ||
      Object.keys(registryEntry).length !== 1
    ) {
      throw new Error(`expo-lynx-view embedded registry entry is invalid for ${feature}.`);
    }
    const featureDirectory = path.resolve(sourcePath, feature);
    if (
      !isContained(sourcePath, featureDirectory) ||
      !fs.existsSync(featureDirectory) ||
      !fs.lstatSync(featureDirectory).isDirectory()
    ) {
      throw new Error(`expo-lynx-view embedded feature directory is missing for ${feature}.`);
    }
    const baselinePath = resolveEmbeddedPath(
      sourcePath,
      registryEntry.baseline,
      `embedded baseline ${feature}`
    );
    const baseline = parseJSONFile(baselinePath, `embedded baseline ${feature}`);
    if (
      !isPlainObject(baseline) ||
      baseline.schemaVersion !== 2 ||
      baseline.feature !== feature ||
      baseline.entry !== 'main.lynx.bundle' ||
      !Array.isArray(baseline.files)
    ) {
      throw new Error(`expo-lynx-view embedded baseline is malformed for ${feature}.`);
    }
    const actual = runtimeFiles(featureDirectory);
    if (!actual.some((file) => file.path === 'main.lynx.bundle'))
      throw new Error(
        `expo-lynx-view embedded baseline is missing main.lynx.bundle for ${feature}.`
      );
    if (
      actual.length > MAX_ENTRIES ||
      actual.reduce((total, file) => total + file.bytes, 0) > MAX_UNCOMPRESSED_BYTES
    )
      throw new Error(`expo-lynx-view embedded baseline exceeds delivery limits for ${feature}.`);
    const declared = baseline.files.map((file) => {
      if (!isPlainObject(file))
        throw new Error(
          `expo-lynx-view embedded baseline has an invalid file entry for ${feature}.`
        );
      assertSafeRelativePath(file.path, `embedded baseline ${feature}`);
      if (file.path !== 'main.lynx.bundle' && !file.path.startsWith('static/'))
        throw new Error(
          `expo-lynx-view embedded baseline has an unsupported file for ${feature}: ${file.path}`
        );
      if (
        !Number.isSafeInteger(file.bytes) ||
        file.bytes <= 0 ||
        file.bytes > MAX_SINGLE_ENTRY_BYTES
      )
        throw new Error(
          `expo-lynx-view embedded baseline has an invalid file size for ${feature}.`
        );
      assertHash(file.sha256, `embedded baseline ${feature}`);
      return { path: file.path, bytes: file.bytes, sha256: file.sha256 };
    });
    if (JSON.stringify(actual) !== JSON.stringify(declared))
      throw new Error(`expo-lynx-view embedded baseline is stale or incomplete for ${feature}.`);
  }
  const runtime = platform === undefined ? undefined : registry.runtimes[platform];
  if (
    platform !== undefined &&
    (!isPlainObject(runtime) ||
      typeof runtime.runtimeVersion !== 'string' ||
      !runtime.runtimeVersion ||
      typeof runtime.appVersion !== 'string' ||
      !runtime.appVersion ||
      typeof runtime.buildNumber !== 'string' ||
      !runtime.buildNumber)
  ) {
    throw new Error(
      `expo-lynx-view needs a prepared ${platform} runtime. Run lynx host prepare --platform ${platform}.`
    );
  }
  return { registry, features, runtimeVersion: runtime?.runtimeVersion };
}

function writeFeatureDeclaration(sourcePath, features) {
  const declarationPath = path.join(path.dirname(sourcePath), 'lynx-features.d.ts');
  const featureMembers = features
    .map((feature) => `    readonly ${JSON.stringify(feature)}: true;`)
    .join('\n');
  const contents = `// This file is generated by expo-lynx-view during Expo prebuild. Do not edit.\n// It is derived from the validated embedded registry, not from network content.\nimport 'expo-lynx-view';\n\ndeclare module 'expo-lynx-view' {\n  interface ExpoLynxFeatureMap {\n${featureMembers}\n  }\n}\n\nexport {};\n`;
  fs.writeFileSync(declarationPath, contents, { encoding: 'utf8', mode: 0o644 });
  return declarationPath;
}

function copyBundledResource(sourcePath, destinationPath) {
  if (fs.statSync(sourcePath).isDirectory())
    fs.cpSync(sourcePath, destinationPath, { recursive: true, force: true, dereference: false });
  else fs.copyFileSync(sourcePath, destinationPath);
}

function markResourceDirectoryAsFolder(project, xcodePath) {
  const normalizedPath = xcodePath.replace(/\\/g, '/');
  for (const [key, reference] of Object.entries(project.pbxFileReferenceSection())) {
    if (key.endsWith('_comment') || !reference || typeof reference !== 'object') continue;
    const referencePath = String(reference.path || '').replace(/^"|"$/g, '');
    if (referencePath !== normalizedPath) continue;
    reference.lastKnownFileType = 'folder';
    delete reference.explicitFileType;
    delete reference.fileEncoding;
    return;
  }
  throw new Error(
    `expo-lynx-view could not mark the iOS resource directory as a folder: ${xcodePath}`
  );
}

function addResource(project, nativeProjectName, xcodePath, isDirectory) {
  if (!project.hasFile(xcodePath)) {
    project = IOSConfig.XcodeUtils.addResourceFileToGroup({
      filepath: xcodePath,
      groupName: nativeProjectName,
      isBuildFile: true,
      project,
    });
  }
  if (isDirectory) markResourceDirectoryAsFolder(project, xcodePath);
  return project;
}

function validateV2Options(options) {
  const hasEmbedded = options.embeddedBundlesPath !== undefined;
  const hasKey = options.publicKeyPath !== undefined;
  if (hasEmbedded !== hasKey)
    throw new Error(
      'expo-lynx-view embeddedBundlesPath and publicKeyPath must be configured together.'
    );
  if (!hasEmbedded) return null;
  assertKnownKeys(
    options,
    new Set([
      'bundledResources',
      'embeddedBundlesPath',
      'publicKeyPath',
      'deliveryEndpoints',
      'devTool',
    ]),
    'plugin options'
  );
  if (Array.isArray(options.bundledResources) && options.bundledResources.length > 0) {
    throw new Error(
      'expo-lynx-view bundledResources cannot be combined with V2 embeddedBundlesPath; it would duplicate shipped Lynx bytes.'
    );
  }
  return {
    embeddedBundlesPath: options.embeddedBundlesPath,
    publicKeyPath: options.publicKeyPath,
    deliveryEndpoints: options.deliveryEndpoints,
  };
}

function materializeV2Resources({ projectRoot, platformProjectRoot, nativeProjectName, options }) {
  const sourcePath = resolvePlatformEmbeddedBundles(
    projectRoot,
    options.embeddedBundlesPath,
    'ios'
  );
  const publicKeyPath = resolveProjectPath(
    projectRoot,
    options.publicKeyPath,
    'publicKeyPath',
    'file'
  );
  const embedded = validateEmbeddedBundles(sourcePath, 'ios');
  writeFeatureDeclaration(sourcePath, embedded.features);
  // Validate the configured key here as well as in the Info.plist mod. This
  // keeps prebuild failures deterministic even when one platform mod is run
  // independently in introspection tooling.
  normalizePublicKey(publicKeyPath);
  const destinationPath = path.join(platformProjectRoot, nativeProjectName, EMBEDDED_DIRECTORY);
  // This is a plugin-owned generated directory. Replacing it as a unit keeps
  // removed sidecars from surviving a subsequent prebuild.
  fs.rmSync(destinationPath, { recursive: true, force: true });
  fs.mkdirSync(destinationPath, { recursive: true });
  copyBundledResource(sourcePath, destinationPath);
  return destinationPath;
}

function applyV2InfoPlist(infoPlist, projectRoot, options) {
  const publicKeyPath = resolveProjectPath(
    projectRoot,
    options.publicKeyPath,
    'publicKeyPath',
    'file'
  );
  const publicKey = normalizePublicKey(publicKeyPath);
  const embeddedPath = resolveProjectPath(
    projectRoot,
    options.embeddedBundlesPath,
    'embeddedBundlesPath',
    'directory'
  );
  const embedded = validateEmbeddedBundles(embeddedPath, 'ios');
  infoPlist[INFO_PLIST_PUBLIC_KEY] = publicKey.pem;
  infoPlist[INFO_PLIST_PUBLIC_KEY_FINGERPRINT] = publicKey.fingerprint;
  infoPlist[INFO_PLIST_RUNTIME_VERSION] = embedded.runtimeVersion;
  infoPlist[INFO_PLIST_DELIVERY_ENDPOINTS] = normalizeDeliveryEndpoints(
    options.deliveryEndpoints,
    embedded.features
  );
  return infoPlist;
}

function withV2EmbeddedResources(config, v2Options) {
  if (!v2Options) return config;
  return withXcodeProject(config, (projectConfig) => {
    const { platformProjectRoot, projectName, projectRoot } = projectConfig.modRequest;
    const nativeProjectName = projectName || IOSConfig.XcodeUtils.getProjectName(projectRoot);
    materializeV2Resources({
      projectRoot,
      platformProjectRoot,
      nativeProjectName,
      options: v2Options,
    });
    projectConfig.modResults = addResource(
      projectConfig.modResults,
      nativeProjectName,
      `${nativeProjectName}/${EMBEDDED_DIRECTORY}`,
      true
    );
    return projectConfig;
  });
}

function withV2TrustConfiguration(config, v2Options) {
  if (!v2Options) return config;
  return withInfoPlist(config, (infoPlistConfig) => {
    const { projectRoot } = infoPlistConfig.modRequest;
    infoPlistConfig.modResults = applyV2InfoPlist(
      infoPlistConfig.modResults,
      projectRoot,
      v2Options
    );
    return infoPlistConfig;
  });
}

function materializeV2AndroidResources({ projectRoot, options }) {
  const sourcePath = resolvePlatformEmbeddedBundles(
    projectRoot,
    options.embeddedBundlesPath,
    'android'
  );
  const embedded = validateEmbeddedBundles(sourcePath, 'android');
  const publicKeyPath = resolveProjectPath(
    projectRoot,
    options.publicKeyPath,
    'publicKeyPath',
    'file'
  );
  const publicKey = normalizePublicKey(publicKeyPath);
  const assetsDirectory = path.join(projectRoot, 'android', 'app', 'src', 'main', 'assets');
  const embeddedDestination = path.join(assetsDirectory, ANDROID_EMBEDDED_DIRECTORY);
  fs.rmSync(embeddedDestination, { recursive: true, force: true });
  fs.mkdirSync(assetsDirectory, { recursive: true });
  copyBundledResource(sourcePath, embeddedDestination);
  fs.writeFileSync(
    path.join(assetsDirectory, ANDROID_DELIVERY_CONFIGURATION),
    `${JSON.stringify({
      schemaVersion: 1,
      runtimeVersion: embedded.runtimeVersion,
      deliveryEndpoints: normalizeDeliveryEndpoints(options.deliveryEndpoints, embedded.features),
      publicKey: publicKey.pem,
    })}\n`,
    { encoding: 'utf8', mode: 0o644 }
  );
  return {
    embeddedDestination,
    configurationPath: path.join(assetsDirectory, ANDROID_DELIVERY_CONFIGURATION),
  };
}

function resolvePlatformEmbeddedBundles(projectRoot, embeddedBundlesPath, platform) {
  const root = resolveProjectPath(
    projectRoot,
    embeddedBundlesPath,
    'embeddedBundlesPath',
    'directory'
  );
  if (fs.existsSync(path.join(root, 'registry.json'))) return root;
  throw new Error(
    `expo-lynx-view needs an embedded baseline. Run lynx host embed <mini-app-directory>, then lynx host prepare --platform ${platform}.`
  );
}

function withV2AndroidResources(config, v2Options) {
  if (!v2Options) return config;
  return withDangerousMod(config, [
    'android',
    (androidConfig) => {
      materializeV2AndroidResources({
        projectRoot: androidConfig.modRequest.projectRoot,
        options: v2Options,
      });
      return androidConfig;
    },
  ]);
}

function prioritizeExpoImageFramework(project) {
  // ExpoImage bundles SDWebImage; its framework must beat CocoaPods' stub framework.
  const [, target] = IOSConfig.Target.findFirstNativeTarget(project);
  const list = project.pbxXCConfigurationList()[target.buildConfigurationList];
  const configurations = project.pbxXCBuildConfigurationSection();
  const expoImagePath = '"$(PODS_XCFRAMEWORKS_BUILD_DIR)/ExpoImage"';
  for (const { value } of list.buildConfigurations) {
    const settings = configurations[value].buildSettings;
    const existing = settings.FRAMEWORK_SEARCH_PATHS;
    const paths = Array.isArray(existing) ? existing : existing ? [existing] : ['$(inherited)'];
    settings.FRAMEWORK_SEARCH_PATHS = [
      expoImagePath,
      ...paths
        .filter((path) => path !== expoImagePath)
        .map((path) => (path === '$(inherited)' ? '"$(inherited)"' : path)),
    ];
  }
  return project;
}

function hasExpoImage(projectRoot) {
  try {
    require.resolve('expo-image/package.json', { paths: [projectRoot] });
    return true;
  } catch {
    return false;
  }
}

function withExpoImageFrameworkSearchPath(config) {
  return withXcodeProject(config, (projectConfig) => {
    if (!hasExpoImage(projectConfig.modRequest.projectRoot)) return projectConfig;
    projectConfig.modResults = prioritizeExpoImageFramework(projectConfig.modResults);
    return projectConfig;
  });
}

function withBundledResources(config, bundledResources) {
  if (!bundledResources.length) return config;
  config = withXcodeProject(config, (projectConfig) => {
    const { platformProjectRoot, projectName, projectRoot } = projectConfig.modRequest;
    const nativeProjectName = projectName || IOSConfig.XcodeUtils.getProjectName(projectRoot);
    for (const resourcePath of bundledResources) {
      const sourcePath = path.resolve(projectRoot, resourcePath);
      if (!fs.existsSync(sourcePath))
        throw new Error(`expo-lynx-view bundled resource does not exist: ${resourcePath}`);
      const filename = path.basename(sourcePath);
      const xcodePath = `${nativeProjectName}/${filename}`;
      copyBundledResource(sourcePath, path.join(platformProjectRoot, nativeProjectName, filename));
      projectConfig.modResults = addResource(
        projectConfig.modResults,
        nativeProjectName,
        xcodePath,
        fs.statSync(sourcePath).isDirectory()
      );
    }
    return projectConfig;
  });
  return withDangerousMod(config, [
    'android',
    (androidConfig) => {
      const { projectRoot } = androidConfig.modRequest;
      const androidAssetsDir = path.join(projectRoot, 'android', 'app', 'src', 'main', 'assets');
      fs.mkdirSync(androidAssetsDir, { recursive: true });
      for (const resourcePath of bundledResources) {
        const sourcePath = path.resolve(projectRoot, resourcePath);
        if (!fs.existsSync(sourcePath))
          throw new Error(`expo-lynx-view bundled resource does not exist: ${resourcePath}`);
        copyBundledResource(sourcePath, path.join(androidAssetsDir, path.basename(sourcePath)));
      }
      return androidConfig;
    },
  ]);
}

const withExpoLynx = (config, options = {}) => {
  const v2Options = validateV2Options(options);
  const devTool = resolveDevToolOption(options);
  const bundledResources = options.bundledResources || [];
  if (
    !Array.isArray(bundledResources) ||
    !bundledResources.every((value) => typeof value === 'string')
  )
    throw new Error('expo-lynx-view bundledResources must be a string array.');
  config = withPodfile(config, (podfileConfig) => {
    let { contents } = podfileConfig.modResults;
    contents = addExpoLynxPostInstall(contents);
    contents = addExpoLynxSpecsSource(contents);
    // LynxDevtool (source-built) reaches into Lynx's internal C++ headers by
    // their nested source path, which the precompiled xcframework can't
    // provide (see addExpoLynxPrecompiledPod). Skip the :path override
    // whenever devTool is on so Lynx resolves from source instead.
    contents = devTool
      ? removeExpoLynxPrecompiledPod(contents)
      : addExpoLynxPrecompiledPod(contents);
    contents = devTool ? addExpoLynxDevtoolPod(contents) : removeExpoLynxDevtoolPod(contents);
    podfileConfig.modResults.contents = contents;
    return podfileConfig;
  });
  config = withV2EmbeddedResources(config, v2Options);
  config = withV2TrustConfiguration(config, v2Options);
  config = withV2AndroidResources(config, v2Options);
  config = withExpoImageFrameworkSearchPath(config);
  return withBundledResources(config, bundledResources);
};

const plugin = createRunOncePlugin(withExpoLynx, packageJSON.name, packageJSON.version);
module.exports = plugin;
module.exports._internal = {
  EMBEDDED_DIRECTORY,
  INFO_PLIST_PUBLIC_KEY,
  INFO_PLIST_PUBLIC_KEY_FINGERPRINT,
  INFO_PLIST_DELIVERY_ENDPOINTS,
  INFO_PLIST_RUNTIME_VERSION,
  ANDROID_DELIVERY_CONFIGURATION,
  ANDROID_EMBEDDED_DIRECTORY,
  addExpoLynxPostInstall,
  addExpoLynxSpecsSource,
  addExpoLynxPrecompiledPod,
  removeExpoLynxPrecompiledPod,
  addExpoLynxDevtoolPod,
  removeExpoLynxDevtoolPod,
  resolveDevToolOption,
  mergeContents,
  addResource,
  hasExpoImage,
  prioritizeExpoImageFramework,
  applyV2InfoPlist,
  materializeV2Resources,
  materializeV2AndroidResources,
  resolvePlatformEmbeddedBundles,
  normalizePublicKey,
  normalizeDeliveryEndpoints,
  resolveProjectPath,
  validateEmbeddedBundles,
  writeFeatureDeclaration,
  validateV2Options,
};
